name: Trigger auto deployment for authentication-microservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/authentication-microservice-AutoDeployTrigger-ea5c37b7-9ed7-40d6-9b26-bc93b037d420.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AUTHENTICATIONMICROSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTHENTICATIONMICROSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTHENTICATIONMICROSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: AuthenticationMicroservice/Dockerfile
          # _dockerfilePathKey_: _dockerfilePath_
          registryUrl: containerregistryecommerce.azurecr.io
          registryUsername: ${{ secrets.AUTHENTICATIONMICROSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTHENTICATIONMICROSERVICE_REGISTRY_PASSWORD }}
          containerAppName: authentication-microservice
          resourceGroup: MovieShoprg
          imageToBuild: containerregistryecommerce.azurecr.io/authentication-microservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


