name: Trigger auto deployment for order-microservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/order-microservice-AutoDeployTrigger-39f7ef59-f7ef-4811-a044-7ca91584a139.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORDERMICROSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORDERMICROSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORDERMICROSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/OrderMicroservice/Dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: containerregistryecommerce.azurecr.io
          registryUsername: ${{ secrets.ORDERMICROSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORDERMICROSERVICE_REGISTRY_PASSWORD }}
          containerAppName: order-microservice
          resourceGroup: MovieShoprg
          imageToBuild: containerregistryecommerce.azurecr.io/order-microservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


